apiVersion: apps/v1
kind: Deployment
metadata:
  name: arkon-python
  labels:
    app: arkon-python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arkon-python
  template:
    metadata:
      labels:
        app: arkon-python
    spec:
      containers:
        - name: arkon-python
          image: 130189/arkon-python:develop
          imagePullPolicy: Always
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: arkon-python
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: arkon-python
  ports:
    - port: 5000
      targetPort: 5000
